function checkFoodSafety() {
    const foodInput = document.getElementById("foodInput").value.toLowerCase();
    const result = document.getElementById("result");

    if (safeFoodsForDogs.includes(foodInput)) {
        result.textContent = `${foodInput.charAt(0).toUpperCase() + foodInput.slice(1)} is safe for canine consumption.`;
    } else {
        if (modFoodsForDogs.includes(foodInput)) {
        result.textContent = `${foodInput.charAt(0).toUpperCase() + foodInput.slice(2)} is safe in moderation for canine consumption.`;
    } else (toxicFoodsForDogs.includes(foodInput)) {
        result.textContent = `${foodInput.charAt(0).toUpperCase() + foodInput.slice(3)} is toxic for canine consumption.</n>If ingested, please contact your emergency vet.`;
    }
}

const safeFoodsForDogs = [
    "Apple",
    "Apples",
    "Asparagus",
    "Banana",
    "Bananas",
    "Beef",
    "Bell Pepper",
    "Bison",
    "Black Beans",
    "Blackberries",
    "Blackberry",
    "Blueberries",
    "Blueberry",
    "Bread",
    "Brisket",
    "Broccoli",
    "Broccolini",
    "Butternut Squash",
    "Cantaloupe",
    "Carrot",
    "Carrots",
    "Celery",
    "Chestnuts",
    "Chicken",
    "Chuck Steak",
    "Cod",
    "Corn",
    "Cranberries",
    "Cranberry",
    "Cucumber",
    "Cucumbers",
    "Duck",
    "Egg",
    "Eggs",
    "Garbanzo Beans",
    "Grain",
    "Grains",
    "Green Bean",
    "Green Beans",
    "Ground Beef",
    "Lamb",
    "Lima Beans",
    "Liver",
    "Mango",
    "Mangoes",
    "Oatmeal",
    "Oats",
    "Pea",
    "Peach",
    "Peaches",
    "Peanut Butter",
    "Pear",
    "Pears",
    "Peas",
    "Pineapple",
    "Pinto Beans",
    "Popcorn, plain",
    "Pork",
    "Potato, cooked",
    "Potatoes, cooked",
    "Pumpkin",
    "Pumpkins",
    "Rabbit",
    "Red Pepper",
    "Rice",
    "Salmon, cooked",
    "Sardines",
    "Shrimp",
    "Snap Peas",
    "Soybeans",
    "Strawberries",
    "Strawberry",
    "Sweet Potato",
    "Sweet Potatoes",
    "Swiss Chard",
    "Tomatoes, ripe",
    "Tuna",
    "Turkey",
    "Watermelon",
    // ... add other safe foods here
];

const modFoodsForDogs = [
    "Apple Cider Vinegar",
    "Bacon",
    "Basil",
    "Brazil Nuts",
    "Brussel Sprouts, cooked",
    "Cabbage",
    "Cashew",
    "Cashews",
    "Cauliflower",
    "Caviar",
    "Cheese",
    "Cherries, pitted",
    "Chia",
    "Cinnamon",
    "Clove",
    "Cloves",
    "Coconut",
    "Coriander",
    "Cottage Cheese",
    "Dairy",
    "Date",
    "Dates",
    "Dill",
    "Fennel",
    "Fenugreek",
    "Fermented",
    "Fig",
    "Figs",
    "Flaxseed",
    "Ginger",
    "Goat Cheese",
    "Ham",
    "Honey",
    "Hot dog",
    "Hot dogs",
    "Kale",
    "Kefir",
    "Kidney Beans",
    "Lettuce",
    "Marshmallow",
    "Marshmallows",
    "Mayo",
    "Mayonnaise",
    "Milk",
    "Millet",
    "Mint",
    "Olive",
    "Olives",
    "Orange",
    "Oranges",
    "Oregano",
    "Paprika",
    "Parsley",
    "Peanut",
    "Peanuts",
    "Quinoa",
    "Raspberries",
    "Raspberry",
    "Roast Beef",
    "Salt",
    "Spinach",
    "Spirulina",
    "Tomato",
    "Tomatoes",
    "Turmeric",
    "Yogurt",
    "Zucchini",
    // ... add other mod safe foods here
];

const toxicFoodsForDogs = [
    "Alcohol",
    "Allium",
    "Almond",
    "Almonds",
    "Avocado",
    "Avocados",
    "Baked Beans",
    "Bay Leaf",
    "Bay Leaves",
    "Beer",
    "Black Walnut",
    "Black Walnuts",
    "Bones",
    "Bourbon",
    "Caffeine",
    "Chili Beans",
    "Chive",
    "Chives",
    "Chocolate",
    "Cob",
    "Cocoa",
    "Coffee",
    "Curry",
    "Eggplant",
    "Energy Drink",
    "English Walnut",
    "English Walnuts",
    "Ethanol",
    "Garlic",
    "Gin",
    "Grape",
    "Grapes",
    "Green Pepper",
    "Green Peppers",
    "Hickory Nut",
    "Hickory Nuts",
    "Hot Pepper",
    "Hot Peppers",
    "Ice Cream",
    "Japanese Walnut",
    "Japanese Walnuts",
    "Leek",
    "Leeks",
    "Macadamia Nut",
    "Macadamia Nuts",
    "Mushroom",
    "Mushrooms",
    "Mustard",
    "Nutmeg",
    "Onion",
    "Onions",
    "Pecan",
    "Pecans",
    "Pickle",
    "Pickles",
    "Pistachio",
    "Pistachios",
    "Pit",
    "Pits",
    "Pop",
    "Pudding",
    "Raisin",
    "Raisins",
    "Refried Beans",
    "Rhubarb",
    "Rum",
    "Scallion",
    "Scallions",
    "Seed, fruit",
    "Seeds, fruit",
    "Shallot",
    "Shallots",
    "Soda",
    "Sports Drink",
    "Spring Onion",
    "Spring Onions",
    "Tea",
    "Wild Garlic",
    "Lemons",
    "Lemon",
    "Lime",
    "Limes",
    "Wine",
    "Xylitol",
    "Yeast Dough",
    "Yellow Pepper",
    "Yellow Peppers",
    // ... add other toxic foods here
];

